defaults:
  - model: default.yaml
  - annotator: default.yaml
  - _self_

  # enable color logging
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}

# path to directory where images are saved 
save_dir: /itf-fi-ml/shared/users/poyenyt/slice-and-view/NLM9-2_output_framboid

#${original_work_dir}/test_data/cauliflower2_magnetite_mask

# checkpoint path of the lightning module
ckpt_path: ${original_work_dir}/_NLM9-2_fram_plaque/checkpoints/_NLM9-2_fram_plaque/149_0.056.ckpt

# path for segmentation
query_img_path: /itf-fi-ml/shared/users/poyenyt/slice-and-view/NLM9_2
support_imgs_dir: ${original_work_dir}/test_data/NLM9-2/framboid/image
support_annots_dir: ${original_work_dir}/test_data/NLM9-2/framboid/annotation
output_dir: ${save_dir}/outputs

# change the default directory of hydra output
hydra:
    output_subdir: ${save_dir}

model:
    backbone: vgg16
    
annotator:
    down_sampling: 4
    patch_width: 224
    patch_height: 224
    margin: 32
    batch_size: 10
    keep_dim: True
    save_init_imgs: False
    cuda_device: 0


# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# default name for the experiment, determines logging folder path
# (you can overwrite this name in experiment configs)
name: "default"
