model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/val_loss" # name of the logged metric which determines when model is improving
  mode: "min" # "max" means higher metric value is better, can be also "min"
  save_top_k: 20 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  every_n_epochs: null
  verbose: False
  dirpath: null
  filename: null
  auto_insert_metric_name: False

# early_stopping:
#   _target_: pytorch_lightning.callbacks.EarlyStopping
#   monitor: "precision" # name of the logged metric which determines when model is improving
#   mode: "max" # "max" means higher metric value is better, can be also "min"
#   patience: 100 # how many validation epochs of not improving until training stops
#   min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement

# model_summary:
#   _target_: pytorch_lightning.callbacks.RichModelSummary
#   max_depth: -1

progress_bar:
  _target_: pytorch_lightning.callbacks.progress.RichProgressBar
  refresh_rate: 1

